config/routes.rb
Rails.application.routes.draw do
  
  namespace :dynamic_select do
    get ':food_item_id/measurements', to: 'food_item_measurements#index', as: 'food_item_measurements'
  end
  
  resources :measurements, only: [:show, :edit, :update, :destroy]
  resources :food_items do
    resources :measurements, only: [:new, :create]
  end
  
  resources :meals
  
  resources :ingredients, only: [:show, :edit, :update, :destroy]
  resources :recipes do
    resources :ingredients, only: [:new, :create]
  end
  
  get  'welcome', to: 'welcome#index'
  root 'welcome#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  
  has_many :ingredients, dependent: :destroy
  
  before_validation :update_cached_values
  
  validates :title, uniqueness: true
  validates :title, :description, :instructions, presence: true
  validates :servings, numericality: :greater_than_or_equal_to_zero
  
  def update_cached_values
    self.calories = self.ingredients.sum(:calories)
    self.protein = self.ingredients.sum(:protein)
    self.carbs = self.ingredients.sum(:carbs)
    self.fat = self.ingredients.sum(:fat)
    self.fiber = self.ingredients.sum(:fiber)
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.order(title: :asc)
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:title, :description, :instructions, :servings)
    end
end

app/views/recipes/_form.html.erb
<!-- Errors -->
<%= bootstrap_errors f %>

<!-- Title -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :title)}") do %>
  <%= f.label :title, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :title, placeholder: Recipe.human_attribute_name(:title), class: "form-control" %>
  </div>
<% end %>

<!-- Description -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :description)}") do %>
  <%= f.label :description, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_area :description, placeholder: Recipe.human_attribute_name(:description), class: "form-control", rows: "10" %>
  </div>
<% end %>

<% if f.object.new_record? -%>
  <%= content_tag(:div, class: "form-group") do %>
    <%= f.label :ingredients, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <p class="form-control-static">Ingredients can be added after the Recipe is created.</p>
    </div>
  <% end %>
<% end -%>

<!-- Instructions -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :instructions)}") do %>
  <%= f.label :instructions, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_area :instructions, placeholder: Recipe.human_attribute_name(:instructions), class: "form-control", rows: "10" %>
  </div>
<% end %>

<!-- Servings -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :servings)}") do %>
  <%= f.label :servings, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :servings, placeholder: Recipe.human_attribute_name(:servings), class: "form-control", rows: "10" %>
  </div>
<% end %>


<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-default" %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="page-header">
  <h2><%= I18n.t("headers.edit", model_name: Recipe.model_name.human) %></h2>
</div>

<ul class="nav nav-tabs">
	<%= tab("List", recipes_path, "fa fa-list") %>
  <%= tab "Add New", new_recipe_path, "fa fa-plus" %>
  <%= tab "Details", @recipe, "fa fa-info-circle" %>
  <%= active_tab "Edit", edit_recipe_path(@recipe), "fa fa-pencil-square-o" %>
</ul>

<%= form_for(@recipe, html: { class: "edit_recipe form-horizontal", role: "form" }) do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/recipes/index.html.erb
<div class="page-header">
  <h2><%= Recipe.model_name.human.pluralize %></h2>
</div>

<ul class="nav nav-tabs">
	<%= active_tab("List", recipes_path, "fa fa-list") %>
  <%= tab "Add New", new_recipe_path, "fa fa-plus" %>
  <%= disabled_tab "Details", "fa fa-info-circle" %>
  <%= disabled_tab "Edit", "fa fa-pencil-square-o" %>
</ul>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th><%= Recipe.human_attribute_name(:title) %></th>
      <th nowrap class="shrink"><%= Recipe.human_attribute_name(:calories) %></th>
      <th nowrap class="shrink"><%= Recipe.human_attribute_name(:fat) %></th>
      <th nowrap class="shrink"><%= Recipe.human_attribute_name(:carbs) %></th>
      <th nowrap class="shrink"><%= Recipe.human_attribute_name(:fiber) %></th>
      <th nowrap class="shrink"><%= Recipe.human_attribute_name(:protein) %></th>
      <th nowrap class="shrink"><%= Recipe.human_attribute_name(:servings) %></th>

      <th class="shrink"></th>
      <th class="shrink"></th>
      <th class="shrink"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td class="text-right"><%= recipe.calories %></td>
        <td class="text-right"><%= recipe.fat %></td>
        <td class="text-right"><%= recipe.carbs %></td>
        <td class="text-right"><%= recipe.fiber %></td>
        <td class="text-right"><%= recipe.protein %></td>
        <td class="text-right"><%= recipe.servings %></td>

        <td>
          <%= link_to recipe, title: "Details", data: { toggle: "tooltip" } do %>
            <span class="fa fa-info-circle"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_recipe_path(recipe), title: "Edit", data: { toggle: "tooltip" } do %>
            <span class="fa fa-pencil-square-o"></span>
          <% end %>
        </td>
        <td>
          <%= link_to recipe, method: :delete, title: "Delete", data: { toggle: "tooltip", confirm: 'Are you sure?' } do %>
            <span class="fa fa-trash-o"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/new.html.erb
<div class="page-header">
  <h2><%= I18n.t("headers.new", model_name: Recipe.model_name.human) %></h2>
</div>

<ul class="nav nav-tabs">
	<%= tab("List", recipes_path, "fa fa-list") %>
  <%= active_tab "Add New", new_recipe_path, "fa fa-plus" %>
  <%= disabled_tab "Details", "fa fa-info-circle" %>
  <%= disabled_tab "Edit", "fa fa-pencil-square-o" %>
</ul>

<%= form_for(@recipe, html: { class: "new_recipe form-horizontal", role: "form" }) do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/recipes/show.html.erb
<div class="page-header">
  <h2><%= Recipe.model_name.human %></h2>
</div>

<ul class="nav nav-tabs">
	<%= tab("List", recipes_path, "fa fa-list") %>
  <%= tab "Add New", new_recipe_path, "fa fa-plus" %>
  <%= active_tab "Details", @recipe, "fa fa-info-circle" %>
  <%= tab "Edit", edit_recipe_path(@recipe), "fa fa-pencil-square-o" %>
</ul>

<div class="row">
  <div class="col-lg-9">
    <!-- Description -->
    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h2 class="panel-title">
				      <%= @recipe.title %>
				    </h2>
			    </div>
			
			    <div class="panel-body">
            <%= simple_format @recipe.description %>
          </div>
          </div>
      </div>
    </div>
    
    <!-- Ingredients -->
    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h2 class="panel-title">
				      Ingredients
				    </h2>
			    </div>
			
          <div class="table-responsive">
    		    <table class="table table-condensed">
    		        <thead>
                <tr>
                  <th nowrap class="shrink"><%= Ingredient.human_attribute_name(:quantity) %></th>
                  <th nowrap class="shrink"><%= Ingredient.human_attribute_name(:measurement_name) %></th>
                  <th nowrap class="shrink"><%= Ingredient.human_attribute_name(:prep) %></th>
                  <th><%= Ingredient.human_attribute_name(:food_item_name) %></th>

                  <th class="shrink"></th>
                  <th class="shrink"></th>
                </tr>
              </thead>
          
    			    <tbody>
                <% @recipe.ingredients.order(id: :asc).each do |ingredient| %>
                  <tr>
                    <td class="text-right"><%= ingredient.quantity %></td>
                    <td nowrap><%= ingredient.measurement_name %></td>
                    <td nowrap><%= ingredient.prep %></td>
                    <td><%= ingredient.food_item_name %></td>

                    <td>
                      <%= link_to edit_ingredient_path(ingredient), title: "Edit", data: { toggle: "tooltip" } do %>
                        <span class="fa fa-pencil-square-o"></span>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to ingredient, method: :delete, title: "Delete", data: { toggle: "tooltip", confirm: 'Are you sure?' } do %>
                        <span class="fa fa-trash-o"></span>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
    			    </tbody>
    		    </table>
    		    
    		    <div class="panel-footer">
  				    <%= link_to new_recipe_ingredient_path(@recipe) do %>
  					    <span class="fa fa-plus"></span> Add New
  				    <% end %>
  			    </div>
          </div>			
        </div>
      </div>
    </div>
    
    <!-- Instructions -->
    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h2 class="panel-title">
				      Instructions
				    </h2>
			    </div>
			
			    <div class="panel-body">
            <%= simple_format @recipe.instructions %>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Nutritional Info -->
  <div class="col-lg-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title">
				  Nutritional Info <span class="pull-right"><%= pluralize(@recipe.servings, "Serving") %></span>
				</h2>
			</div>
			
      <div class="table-responsive">
    		<table class="table table-condensed">
    			<tbody>
            <tr>
              <th><%= Recipe.human_attribute_name(:calories) %></th>
              <td class="text-right"><%= @recipe.calories %></td>
              <td class="shrink"> </td>
            </tr>
            
            <tr>
              <th><%= Recipe.human_attribute_name(:fat) %></th>
              <td class="text-right"><%= @recipe.fat %></td>
              <td class="shrink"><%= "Gram".pluralize(@recipe.fat) %></td>
            </tr>
            
            <tr>
              <th><%= Recipe.human_attribute_name(:carbs) %></th>
              <td class="text-right"><%= @recipe.carbs %></td>
              <td class="shrink"><%= "Gram".pluralize(@recipe.carbs) %></td>
            </tr>
            
            <tr>
              <th><%= Recipe.human_attribute_name(:fiber) %></th>
              <td class="text-right"><%= @recipe.fiber %></td>
              <td class="shrink"><%= "Gram".pluralize(@recipe.fiber) %></td>
            </tr>
            
            <tr>
              <th><%= Recipe.human_attribute_name(:protein) %></th>
              <td class="text-right"><%= @recipe.protein %></td>
              <td class="shrink"><%= "Gram".pluralize(@recipe.protein) %></td>
            </tr>
    			</tbody>
    		</table>
      </div>
			
    </div>
  </div>
</div>