config/routes.rb
Rails.application.routes.draw do
  
  namespace :dynamic_select do
    get ':food_item_id/measurements', to: 'food_item_measurements#index', as: 'food_item_measurements'
  end
  
  resources :measurements, only: [:show, :edit, :update, :destroy]
  resources :food_items do
    resources :measurements, only: [:new, :create]
  end
  
  resources :meals
  
  resources :ingredients, only: [:show, :edit, :update, :destroy]
  resources :recipes do
    resources :ingredients, only: [:new, :create]
  end
  
  get  'welcome', to: 'welcome#index'
  root 'welcome#index'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  
  belongs_to :recipe
  belongs_to :food_item
  belongs_to :measurement
  
  before_validation :update_cached_values
  
  after_save :update_recipe
  after_destroy :update_recipe
  
  validates :food_item_id, uniqueness: { scope: :recipe_id }
  validates :quantity, numericality: :greater_than_or_equal_to_zero
  
  def food_item_name
    self.food_item.name
  end
  
  def measurement_name
    name = self.measurement.singular_name.pluralize(self.quantity)
    name += ", #{self.measurement.prep}" unless self.measurement.prep.blank?
    return name
  end
  
  def update_cached_values
    if quantity && food_item
      self.calories = self.quantity * food_item.calories
      self.protein = self.quantity * food_item.protein
      self.carbs = self.quantity * food_item.carbs
      self.fat = self.quantity * food_item.fat
      self.fiber = self.quantity * food_item.fiber
    end
  end
  
  def update_recipe
    recipe.update_cached_values
    recipe.save(validate: false)
  end
  
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_recipe, only: [:new, :create]
  before_action :set_ingredient, only: [:edit, :update, :destroy]

  def new
    @ingredient = @recipe.ingredients.build
  end

  def edit
    @recipe = @ingredient.recipe
  end

  def create
    @ingredient = @recipe.ingredients.build(ingredient_params)

    if @ingredient.save
      redirect_to @recipe, notice: 'Ingredient was successfully created.'
    else
      render :new
    end
  end

  def update
    @recipe = @ingredient.recipe
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient.recipe, notice: 'Ingredient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipe = @ingredient.recipe
    @ingredient.destroy
    redirect_to @recipe, notice: 'Ingredient was successfully destroyed.'
  end

  private
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end
    
    def set_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end

    def ingredient_params
      params.require(:ingredient).permit(:food_item_id, :measurement_id, :prep, :quantity)
    end
end

app/views/ingredients/_form.html.erb
<!-- Errors -->
<%= bootstrap_errors f %>

<!-- Food Item -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :food_item)}") do %>
  <%= f.label :food_item_id, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.collection_select :food_item_id, FoodItem.order(name: :asc), :id, :name, { include_blank: true }, { class: "form-control", data: { dynamic_selectable_url: dynamic_select_food_item_measurements_path(':food_item_id', format: :json), dynamic_selectable_target: '#ingredient_measurement_id' } } %>
  </div>
<% end %>

<!-- Quantity -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :quantity) || has_error(f.object, :measurement)}") do %>
  <%= f.label :quantity, class: "col-sm-2 control-label" %>
  <div class="col-sm-2">
    <%= f.text_field :quantity, placeholder: Ingredient.human_attribute_name(:quantity), class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <%= f.collection_select :measurement_id, f.object.try(:food_item).try(:measurements) || [ ], :id, :name, { include_blank: true }, { class: "form-control" } %>
  </div>
<% end %>

<!-- Prep -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :prep)}") do %>
  <%= f.label :prep, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :prep, placeholder: Ingredient.human_attribute_name(:prep), class: "form-control" %>
  </div>
<% end %>


<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-default" %>
  </div>
</div>

app/views/ingredients/edit.html.erb
<div class="page-header">
  <h2><%= I18n.t("headers.edit", model_name: Ingredient.model_name.human) %> <small>for <%= link_to @recipe.title, @recipe %></small></h2>
</div>

<%= form_for(@ingredient, html: { class: "edit_ingredient form-horizontal", role: "form" }) do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/ingredients/new.html.erb
<div class="page-header">
  <h2><%= I18n.t("headers.new", model_name: Ingredient.model_name.human) %> <small>for <%= link_to @recipe.title, @recipe %></small></h2>
</div>

<%= form_for([@recipe, @ingredient], html: { class: "new_ingredient form-horizontal", role: "form" }) do |f| %>
  <%= render 'form', f: f %>
<% end %>