config/routes.rb
Rails.application.routes.draw do
  
  namespace :dynamic_select do
    get ':food_item_id/measurements', to: 'food_item_measurements#index', as: 'food_item_measurements'
  end
  
  resources :measurements, only: [:show, :edit, :update, :destroy]
  resources :food_items do
    resources :measurements, only: [:new, :create]
  end
  
  resources :meals
  
  resources :ingredients, only: [:show, :edit, :update, :destroy]
  resources :recipes do
    resources :ingredients, only: [:new, :create]
  end
  
  get  'welcome', to: 'welcome#index'
  root 'welcome#index'
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  
  has_many :measurements, dependent: :destroy
  
  validates :name, uniqueness: { scope: :brand }
  validates :name, :si_units, presence: true
  validates :calories, :protein, :carbs, :fat, :fiber, :si_dimension, numericality: :greater_than_or_equal_to_zero

end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  def index
    @food_items = FoodItem.order(name: :asc)
  end

  def show
  end

  def new
    @food_item = FoodItem.new
  end

  def edit
  end

  def create
    @food_item = FoodItem.new(food_item_params)

    if @food_item.save
      redirect_to @food_item, notice: 'Food Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @food_item.update(food_item_params)
      redirect_to @food_item, notice: 'Food Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @food_item.destroy
    redirect_to food_items_url, notice: 'Food Item was successfully destroyed.'
  end

  private
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :brand, :calories, :protein, :carbs, :fat, :fiber, :si_dimension, :si_units)
    end
end

app/views/food_items/_form.html.erb
<!-- Errors -->
<%= bootstrap_errors f %>

<!-- Name -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :name)}") do %>
  <%= f.label :name, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :name, placeholder: FoodItem.human_attribute_name(:name), class: "form-control" %>
  </div>
<% end %>

<!-- Brand -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :brand)}") do %>
  <%= f.label :brand, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :brand, placeholder: FoodItem.human_attribute_name(:brand), class: "form-control" %>
  </div>
<% end %>

<!-- Calories -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :calories)}") do %>
  <%= f.label :calories, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :calories, placeholder: FoodItem.human_attribute_name(:calories), class: "form-control" %>
  </div>
<% end %>

<!-- Fat -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :fat)}") do %>
  <%= f.label :fat, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <div class="input-group">
      <%= f.text_field :fat, placeholder: FoodItem.human_attribute_name(:fat), class: "form-control" %>
      <span class="input-group-addon" >Grams</span>
    </div>
  </div>
<% end %>

<!-- Carbs -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :carbs)}") do %>
  <%= f.label :carbs, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <div class="input-group">
      <%= f.text_field :carbs, placeholder: FoodItem.human_attribute_name(:carbs), class: "form-control" %>
      <span class="input-group-addon" >Grams</span>
    </div>
  </div>
<% end %>

<!-- Fiber -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :fiber)}") do %>
  <%= f.label :fiber, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <div class="input-group">
      <%= f.text_field :fiber, placeholder: FoodItem.human_attribute_name(:fiber), class: "form-control" %>
      <span class="input-group-addon" >Grams</span>
    </div>
  </div>
<% end %>

<!-- Protein -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :protein)}") do %>
  <%= f.label :protein, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <div class="input-group">
      <%= f.text_field :protein, placeholder: FoodItem.human_attribute_name(:protein), class: "form-control" %>
      <span class="input-group-addon" >Grams</span>
    </div>
  </div>
<% end %>

<!-- SI Dimension/Units -->
<%= content_tag(:div, class: "form-group #{has_error(f.object, :si_dimension) || has_error(f.object, :si_units)}") do %>
  <%= f.label :si_dimension, class: "col-sm-2 control-label" %>
  <div class="col-sm-2">
    <%= f.text_field :si_dimension, placeholder: FoodItem.human_attribute_name(:si_dimension), class: "form-control" %>
  </div>
  <div class="col-sm-8">
    <%= f.select :si_units, Units::SI_UNITS, { include_blank: false }, { class: "form-control" } %>
  </div>
<% end %>


<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-default" %>
  </div>
</div>

app/views/food_items/edit.html.erb
<div class="page-header">
  <h2><%= I18n.t("headers.edit", model_name: FoodItem.model_name.human) %></h2>
</div>

<ul class="nav nav-tabs">
	<%= tab("List", food_items_path, "fa fa-list") %>
  <%= tab "Add New", new_food_item_path, "fa fa-plus" %>
  <%= tab "Details", @food_item, "fa fa-info-circle" %>
  <%= active_tab "Edit", edit_food_item_path(@food_item), "fa fa-pencil-square-o" %>
</ul>

<%= form_for(@food_item, html: { class: "edit_food_item form-horizontal", role: "form" }) do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/food_items/index.html.erb
<div class="page-header">
  <h2><%= FoodItem.model_name.human.pluralize %></h2>
</div>

<ul class="nav nav-tabs">
	<%= active_tab("List", food_items_path, "fa fa-list") %>
  <%= tab "Add New", new_food_item_path, "fa fa-plus" %>
  <%= disabled_tab "Details", "fa fa-info-circle" %>
  <%= disabled_tab "Edit", "fa fa-pencil-square-o" %>
</ul>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th nowrap class="shrink"><%= FoodItem.human_attribute_name(:name) %></th>
      <th><%= FoodItem.human_attribute_name(:brand) %></th>
      <th nowrap class="shrink"><%= FoodItem.human_attribute_name(:calories) %></th>
      <th nowrap class="shrink"><%= FoodItem.human_attribute_name(:fat) %></th>
      <th nowrap class="shrink"><%= FoodItem.human_attribute_name(:carbs) %></th>
      <th nowrap class="shrink"><%= FoodItem.human_attribute_name(:fiber) %></th>
      <th nowrap class="shrink"><%= FoodItem.human_attribute_name(:protein) %></th>
      <th nowrap class="shrink"><%= FoodItem.human_attribute_name(:si_dimension) %></th>
      <th nowrap class="shrink"><%= FoodItem.human_attribute_name(:si_units) %></th>
      
      <th class="shrink"></th>
      <th class="shrink"></th>
      <th class="shrink"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td nowrap><%= food_item.name %></td>
        <td><%= food_item.brand %></td>
        <td class="text-right"><%= food_item.calories %></td>
        <td class="text-right"><%= food_item.fat %></td>
        <td class="text-right"><%= food_item.carbs %></td>
        <td class="text-right"><%= food_item.fiber %></td>
        <td class="text-right"><%= food_item.protein %></td>
        <td class="text-right"><%= food_item.si_dimension %></td>
        <td><%= food_item.si_units.pluralize(food_item.si_dimension) %></td>
        
        <td>
          <%= link_to food_item, title: "Details", data: { toggle: "tooltip" } do %>
            <span class="fa fa-info-circle"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_food_item_path(food_item), title: "Edit", data: { toggle: "tooltip" } do %>
            <span class="fa fa-pencil-square-o"></span>
          <% end %>
        </td>
        <td>
          <%= link_to food_item, method: :delete, title: "Delete", data: { toggle: "tooltip", confirm: 'Are you sure?' } do %>
            <span class="fa fa-trash-o"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/food_items/new.html.erb
<div class="page-header">
  <h2><%= I18n.t("headers.new", model_name: FoodItem.model_name.human) %></h2>
</div>

<ul class="nav nav-tabs">
	<%= tab("List", food_items_path, "fa fa-list") %>
  <%= active_tab "Add New", new_food_item_path, "fa fa-plus" %>
  <%= disabled_tab "Details", "fa fa-info-circle" %>
  <%= disabled_tab "Edit", "fa fa-pencil-square-o" %>
</ul>

<%= form_for(@food_item, html: { class: "new_food_item form-horizontal", role: "form" }) do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/food_items/show.html.erb
<div class="page-header">
  <h2><%= FoodItem.model_name.human %></h2>
</div>

<ul class="nav nav-tabs">
	<%= tab("List", food_items_path, "fa fa-list") %>
  <%= tab "Add New", new_food_item_path, "fa fa-plus" %>
  <%= active_tab "Details", @food_item, "fa fa-info-circle" %>
  <%= tab "Edit", edit_food_item_path(@food_item), "fa fa-pencil-square-o" %>
</ul>

<!-- Food Item -->
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title">
				  <%= @food_item.name %> <small><%= @food_item.brand %></small>
				</h2>
			</div>
			
      <div class="table-responsive">
    		<table class="table table-condensed">
    			<tbody>
            <tr>
              <th><%= FoodItem.human_attribute_name(:calories) %></th>
              <td class="text-right"><%= @food_item.calories %></td>
              <td class="shrink"> </td>
            </tr>
            
            <tr>
              <th><%= FoodItem.human_attribute_name(:fat) %></th>
              <td class="text-right"><%= @food_item.fat %></td>
              <td class="shrink"><%= "Gram".pluralize(@food_item.fat) %></td>
            </tr>
            
            <tr>
              <th><%= FoodItem.human_attribute_name(:carbs) %></th>
              <td class="text-right"><%= @food_item.carbs %></td>
              <td class="shrink"><%= "Gram".pluralize(@food_item.carbs) %></td>
            </tr>
            
            <tr>
              <th><%= FoodItem.human_attribute_name(:fiber) %></th>
              <td class="text-right"><%= @food_item.fiber %></td>
              <td class="shrink"><%= "Gram".pluralize(@food_item.fiber) %></td>
            </tr>
            
            <tr>
              <th><%= FoodItem.human_attribute_name(:protein) %></th>
              <td class="text-right"><%= @food_item.protein %></td>
              <td class="shrink"><%= "Gram".pluralize(@food_item.protein) %></td>
            </tr>
            
            <tr>
              <th><%= FoodItem.human_attribute_name(:si_dimension) %></th>
              <td class="text-right"><%= @food_item.si_dimension %></td>
              <td class="shrink"><%= @food_item.si_units.pluralize(@food_item.si_dimension) %></td>
            </tr>
    			</tbody>
    		</table>
      </div>
    </div>
  </div>
</div>

<!-- Measurements -->
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title">
				  <%= Measurement.model_name.human.pluralize %>
				</h2>
			</div>
			
      <div class="table-responsive">
    		<table class="table table-condensed">
    		    <thead>
            <tr>
              <th class="shrink"> </th>
              <th><%= Measurement.human_attribute_name(:singular_name) %></th>
              <th nowrap class="shrink"><%= Measurement.human_attribute_name(:calories) %></th>
              <th nowrap class="shrink"><%= Measurement.human_attribute_name(:fat) %></th>
              <th nowrap class="shrink"><%= Measurement.human_attribute_name(:carbs) %></th>
              <th nowrap class="shrink"><%= Measurement.human_attribute_name(:fiber) %></th>
              <th nowrap class="shrink"><%= Measurement.human_attribute_name(:protein) %></th>
              <th nowrap class="shrink"><%= Measurement.human_attribute_name(:si_dimension) %></th>
              <th nowrap class="shrink"><%= Measurement.human_attribute_name(:si_units) %></th>
      
              <th class="shrink"></th>
              <th class="shrink"></th>
            </tr>
          </thead>
          
    			<tbody>
            <% @food_item.measurements.order(singular_name: :asc, prep: :asc).each do |measurement| %>
              <tr>
                <td>1</td>
                <td><%= measurement.name %></td>
                <td class="text-right"><%= measurement.calories %></td>
                <td class="text-right"><%= measurement.fat %></td>
                <td class="text-right"><%= measurement.carbs %></td>
                <td class="text-right"><%= measurement.fiber %></td>
                <td class="text-right"><%= measurement.protein %></td>
                <td class="text-right"><%= measurement.si_dimension %></td>
                <td><%= measurement.si_units.pluralize(measurement.si_dimension) %></td>
                
                <td>
                  <%= link_to edit_measurement_path(measurement), title: "Edit", data: { toggle: "tooltip" } do %>
                    <span class="fa fa-pencil-square-o"></span>
                  <% end %>
                </td>
                <td>
                  <%= link_to measurement, method: :delete, title: "Delete", data: { toggle: "tooltip", confirm: 'Are you sure?' } do %>
                    <span class="fa fa-trash-o"></span>
                  <% end %>
                </td>
              </tr>
            <% end %>
    			</tbody>
    		</table>
    		
    		<div class="panel-footer">
  				<%= link_to new_food_item_measurement_path(@food_item) do %>
  					<span class="fa fa-plus"></span> Add New
  				<% end %>
  			</div>
      </div>
    </div>
  </div>
</div>