config/routes.rb
Rails.application.routes.draw do
  
  namespace :dynamic_select do
    get ':food_item_id/measurements', to: 'food_item_measurements#index', as: 'food_item_measurements'
  end
  
  resources :measurements, only: [:show, :edit, :update, :destroy]
  resources :food_items do
    resources :measurements, only: [:new, :create]
  end
  
  resources :meals
  
  resources :ingredients, only: [:show, :edit, :update, :destroy]
  resources :recipes do
    resources :ingredients, only: [:new, :create]
  end
  
  get  'welcome', to: 'welcome#index'
  root 'welcome#index'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="hidden-print alert alert-dismissable alert-<%= name.eql?('notice') ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :p, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
			<%= link_to ENV["WEBSITE_NAME"], root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to FoodItem.model_name.human.pluralize, food_items_path %></li>
				<li><%= link_to "Recipes", recipes_path %></li>
				<li><%= link_to "Meals", meals_path %></li>
				<li><%= link_to "Meal Plans", "#" %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
  <title><%= ENV["WEBSITE_NAME"] %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/navigation' %>

  <div class="container">
		<%= render 'layouts/messages' %>
		<%= yield %>
  </div><!-- /.container -->
</body>

</html>